services:
  poky:
    image: ${POKY_IMAGE}
    container_name: poky_container
    volumes:
      - workdir:/workdir
      - ${PROJECT_TOP}:/workspace
      - ${SSH_PATH}:/home/vari/.ssh
    ports:
      - "${FILEBROWSER_PORT}:9200"
      - "${DL_PORT}:9210"
    environment:
      - WORKDIR_UID=${WORKDIR_UID}
      - WORKDIR_GID=${WORKDIR_GID}
    command: /bin/bash

  filebrowser:
    image: filebrowser/filebrowser
    platform: linux/${ENV_ARCH}
    container_name: filebrowser
    volumes:
      - workdir:/srv
    ports:
      - "${FILEBROWSER_PORT}:80"
    environment:
      - FILEBROWSER_PORT=${FILEBROWSER_PORT}
      - FB_NOAUTH=true

  rpm-host:
    image: httpd:2.4.63-bookworm
    platform: linux/${ENV_ARCH}
    container_name: rpm_host
    volumes:
      - ${SCRIPT_DIR}/conf/httpd-custom.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ${PROJECT_TOP}/poky_tmp/rpm-host-logs:/usr/local/apache2/logs
      - workdir:/usr/local/apache2/htdocs/yocto
    ports:
      - "${DL_PORT}:80"
    environment:
      - DL_PORT=${DL_PORT}
    user: "root"

  nfs-server:
    image: nfs-server-image
    container_name: nfs_server
    volumes:
      - workdir:/workdir
    ports:
      - "2049:2049"
    environment:
      - NFS_EXPORT_PATH=/workdir

networks:
  default:
    driver: bridge

volumes:
  workdir:
    name: ${VOLUME_NAME}_workdir
    external: true
