services:
  vde:
    build:
      dockerfile: Dockerfile_22.04
      context: ./poky-vde
      args:
        USER_ID: ${WORKDIR_UID}
        USER_GID: ${WORKDIR_GID}
        POKY_REPO: https://github.com/yoctoproject/poky.git
        POKY_COMMIT_ID: 6505459809380ddcf152a09343e4dc55038de332
    image: "${POKY_IMAGE}"
    platform: linux/${ENV_ARCH}
    command: [
        "/bin/sh",
        "-c",
        "if [ ! -f /workdir/.initialized ]; then \
        echo 'Workdir starting initialization'; \
        touch /workdir/.initialized && echo 'Workdir created' || echo 'Failed to create workdir'; \
        chown -hR ${WORKDIR_UID}:${WORKDIR_GID} /workdir && echo 'Ownership changed' || echo 'Failed to change ownership'; \
        else \
        echo 'Workdir already initialized'; \
        fi",
      ]
    ports:
      - "${TOASTER_WEBUI}:8000"
    volumes:
      - ${PROJECT_TOP}:${WORKSPACE_PATH}
      - workdir:/workdir
      - ${HOME}/.ssh:/home/vari/.ssh
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # root user is using only for initialization
    user: root
    container_name: "${VOLUME_NAME}_vde"
    hostname: "${VOLUME_NAME}_vde"

  filebrowser:
    image: filebrowser/filebrowser
    platform: linux/${ENV_ARCH}
    container_name: "${VOLUME_NAME}_filebrowser"
    ports:
      - "${FILEBROWSER_PORT}:80"
    volumes:
      - workdir:/srv
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - FB_NOAUTH=true
      - FB_BASEURL=/filebrowser
    depends_on:
      - vde

  rpm-host:
    image: httpd:2.4.63-bookworm
    platform: linux/${ENV_ARCH}
    container_name: "${VOLUME_NAME}_rpm-host"
    ports:
      - ${DL_PORT}:80
    volumes:
      - workdir:/var/www/html/yocto
    depends_on:
      - vde

  netboot-server:
    image: ${NETBOOT_SERVER_IMAGE}
    platform: linux/${ENV_ARCH}
    container_name: "${VOLUME_NAME}_netboot-server"
    privileged: true
    network_mode: "bridge"
    volumes:
      - workdir:/workdir:rw
    ports:
      - "2049:2049/udp"
      - "35111:111/udp"
      - "20048:20048/udp"
      - "32765-32769:32765-32769/udp"
    environment:
      - NFS_SERVER_DEBUG=1
      - NFSROOT_DIR=/workdir/nfsroot
    depends_on:
      - vde

volumes:
  workdir:
    name: ${VOLUME_NAME}_workdir
    external: true
